force-app/main/default/objects/ChangeEventSettings__c/ChangeEventSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ChangeEventSettings</label>
</CustomObject>

force-app/main/default/objects/ChangeEventSettings__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChangeEventTriggerHandler.cls
public with sharing class ChangeEventTriggerHandler {

    
    public static void handle() {
        if(ChangeEventSettings__c.getInstance().enabled__c) {
            doHandle();
        }
    }
    
    private static void doHandle() {

        ChangeEventHandler handler = new ChangeEventHandler();

        if(Trigger.isInsert) {
            handler.handleCreate(Trigger.newMap);    
        }
                
        if(Trigger.isUpdate) {
            handler.handleUpdate(Trigger.newMap,Trigger.oldMap);    
        }
        
        if(Trigger.isDelete) {
            handler.handleDelete(Trigger.oldMap);    
        }
        
        if(Trigger.isUndelete) {
            handler.handleCreate(Trigger.newMap);    
        }

    }

}